### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Caliburnt** [N3rdyR0b1n/Magic-Mayhem#1]
NOT AN ISSUE WITH THE MOD ITSELF BUT SIR, I WANT TO ACTUALLY FOLLOW YOUR DEVELOPMENT BUT ALL YOUR DISCORD LINKS ARE BROKEN! PLEASE!

**Comment by N3rdyR0b1n** [comment]
swag leme fix that

**Comment by N3rdyR0b1n** [comment]
https://discord.gg/ke2KKCgdqp
